
package es.unican.ss.estimaciontusbpel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EstimacionTUSBPEL", targetNamespace = "http://www.unican.es/ss/EstimacionTUSBPEL", wsdlLocation = "http://localhost:8080/ode/processes/EstimacionTUSBPEL?wsdl")
public class EstimacionTUSBPEL
    extends Service
{

    private final static URL ESTIMACIONTUSBPEL_WSDL_LOCATION;
    private final static WebServiceException ESTIMACIONTUSBPEL_EXCEPTION;
    private final static QName ESTIMACIONTUSBPEL_QNAME = new QName("http://www.unican.es/ss/EstimacionTUSBPEL", "EstimacionTUSBPEL");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/ode/processes/EstimacionTUSBPEL?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ESTIMACIONTUSBPEL_WSDL_LOCATION = url;
        ESTIMACIONTUSBPEL_EXCEPTION = e;
    }

    public EstimacionTUSBPEL() {
        super(__getWsdlLocation(), ESTIMACIONTUSBPEL_QNAME);
    }

    public EstimacionTUSBPEL(WebServiceFeature... features) {
        super(__getWsdlLocation(), ESTIMACIONTUSBPEL_QNAME, features);
    }

    public EstimacionTUSBPEL(URL wsdlLocation) {
        super(wsdlLocation, ESTIMACIONTUSBPEL_QNAME);
    }

    public EstimacionTUSBPEL(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ESTIMACIONTUSBPEL_QNAME, features);
    }

    public EstimacionTUSBPEL(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EstimacionTUSBPEL(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EstimacionTUSBPELPortType
     */
    @WebEndpoint(name = "EstimacionTUSBPELPort")
    public EstimacionTUSBPELPortType getEstimacionTUSBPELPort() {
        return super.getPort(new QName("http://www.unican.es/ss/EstimacionTUSBPEL", "EstimacionTUSBPELPort"), EstimacionTUSBPELPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EstimacionTUSBPELPortType
     */
    @WebEndpoint(name = "EstimacionTUSBPELPort")
    public EstimacionTUSBPELPortType getEstimacionTUSBPELPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.unican.es/ss/EstimacionTUSBPEL", "EstimacionTUSBPELPort"), EstimacionTUSBPELPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ESTIMACIONTUSBPEL_EXCEPTION!= null) {
            throw ESTIMACIONTUSBPEL_EXCEPTION;
        }
        return ESTIMACIONTUSBPEL_WSDL_LOCATION;
    }

}
